---
ID: "49e3605c-3add-41eb-8581-e996986767bf"
Parent: "a6100b46-9834-4b01-b6ac-d31bc111fed4"
Template: "a6100b46-9834-4b01-b6ac-d31bc111fed4"
Path: /sitecore/templates/Feature/StandardContent/Prize Items/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T185757Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "d91df154-e551-44e4-a87d-14240068b933"
      Hint: Link Text
      Value: Read More
