---
ID: "d86e1471-be28-41ad-91b2-5fe9b52bcfd8"
Parent: "c59cda37-98cc-47c0-93b9-4cd21317b3ea"
Template: "c59cda37-98cc-47c0-93b9-4cd21317b3ea"
Path: /sitecore/templates/Project/Hackathon/TeamsPage/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{CD1590E1-6573-4CC7-B0A9-E3BB6A9DADE4}">
        <r
          id="{D45B370F-F107-4629-A8F4-1438DAD9A3C5}"
          ph="header"
          uid="{7B6761FB-CC25-48E8-85A3-37F64E1938AC}" />
        <r
          id="{A2294B09-D74C-4557-B337-FA0106FADB5D}"
          ph="main"
          uid="{2ABAFA45-3939-46EC-B8E4-A0B434945D26}" />
        <r
          id="{B3C648F4-3788-42DA-A2BE-D95C904D067B}"
          ph="footer"
          uid="{29C0D2AC-0074-42F6-9844-4DA274F6B625}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T083545Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
