---
ID: "2f0abd9d-d362-4afb-bb12-52f0fd366fe7"
Parent: "2d1afc5c-44ff-4cf8-aa00-93f855eb7b8a"
Template: "2d1afc5c-44ff-4cf8-aa00-93f855eb7b8a"
Path: /sitecore/templates/Feature/Navigation/_NavigationBase/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T213311Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8927c543-e28b-44b9-ad06-dffbb51a471d"
      Hint: Navigation Title
      Value: $name
